### ISSUE TITLE
Hyperlink to edX Theme Repo returns HTTP 404

### ISSUE THREAD

**Issue by RobDolinMS** [appsembler/openedx-azure-fullstack#1]
In ReadMe.md (https://github.com/tkeemon/openedx-azure-fullstack/blob/master/README.md), the hyperlink to the edX Theme Repo results in a HTTP 404 error when clicked.

**Comment by tkeemon** [comment]
Oops. Thanks for catching that @RobDolinMS. 

Fixed: https://github.com/tkeemon/openedx-azure-fullstack/commit/30ca30f384bb71ee52379b8269a0e5df90b15d60
